#########
# PROJECT
#########

# Replace the values here with your project` information.
project:
  # The name of the organisation or entity that owns this project
  organisation: "RJ Gordon"
  # A live web address for the organisation
  url: "http://electricbook.works/"
  # The default contact email address
  email: "rjeremygodon@gmail.com"
  # The name of the project of books in this folder.
  name: "Useful Buddhist Teachings"
  # A one-liner about this project. Useful for Open Graph metadata.
  description: "A book based on posts from the Useful Buddhist Teachings Facebook forum, from 2011-2020."
  # The logo of the organisation, saved web-ready in /assets
  logo: "publisher-logo.jpg"
  # An image in /assets/images/web that stands for the project
  image: "cover.jpg"
  # Credit line, by default in the footer, overidden in locales.yml
  credit: "Built with the [Electric Book](http://electricbook.works)"
  # Primary language code for this project as a whole
  language: "en"
  # App bundle ID unique across all app stores
  app-id: com.example.myapp
  # Version. You must change this with each app update
  version: "1.0.0"


########
# TITLES
########

## Metadata follows [Dublin Core](https://en.wikipedia.org/wiki/Dublin_Core#DCMI_Metadata_Terms)
## Custom fields added to standard DC terms: subtitle, publisher URL
## When listing files, exlude file extensions, and surround them in quotes
## especially if they contain only numbers.

works:
  - directory: "book"
    title: "Useful Buddhist Teachings"
    subtitle: ""
    creator: "RJ Gordon" # E.g. the author
    contributor: "" # E.g. other contributors
    subject: "Spirituality" # E.g. BISAC terms (https://bisg.org/page/BISACEdition) or BIC (http://editeur.dyndns.org/bic_categories)
    description: "A book based on posts from the Useful Buddhist Teachings Facebook forum, from 2011-2020." # E.g. the blurb
    publisher: "" # E.g. the publisher, imprint or brand name
    publisher-url: ""
    date: "2020-08-16" # YYYY-MM-DD e.g. publication date
    modified: "2020-08-16" # YYYY-MM-DD e.g. date of last revision
    type: "Novel" # e.g. Novel, Poetry, Memoir
    identifier: "" # e.g. ISBN or UUID
    source: "" # e.g. parent ISBN or ISTC
    language: "en" # use ISO 639-1, 639-2, or 639-3 codes (in that order of preference)
    relation: "" # e.g. other edition ISBN
    coverage: "" # e.g. geographic place or chronological time span
    rights: "All rights reserved. No part of this book may be reproduced or transmitted in any form or by any electronic or mechanical means, including photocopying and recording, or any other information storage or retrieval system, without written permission from the publisher." # e.g. a copyright statement
    image: "cover.jpg"
    products: # Metadata for each product for this title (only use values that override parent metadata)
      print-pdf: 
        date: "2016-05-07" # YYYY-MM-DD e.g. publication or creation date
        format: "Print" # e.g. Paperback, Digital download, Digital online
        identifier: "" # e.g. ISBN or UUID
        image: "cover.jpg"
        files:
          - "0-1-titlepage"
          # - "0-2-copyright"
          # - "0-3-contents"
          - "01"
          # - "02"
        toc: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
          - label: "Useful Buddhist Teachings"
            file: "01"
      web:
        date: "2016-05-07" # YYYY-MM-DD e.g. publication date or last revision
        format: "Digital online" # e.g. Paperback, Digital download, Digital online
        identifier: "" # e.g. ISBN or UUID
        image: "cover.jpg"
        files:
          - "index"
          - "0-1-titlepage"
          # - "0-2-copyright"
          # - "0-3-contents"
          - "01": "Useful Buddhist Teachings"
        nav: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
          - label: "Frontmatter"
            children:
              - label: "Cover"
                file: "index"
              # - label: "Title page"
              #   file: "0-1-titlepage"
              # - label: "Copyright"
              #   file: "0-2-copyright"
          # - label: "Contents"
          #   file: "0-3-contents"
          - label: "Useful Buddhist Teachings"
            file: "01"
            # id: "1-hello-world"
          # - label: "Chapter Two"
          #   file: "02"
          #   id: "2-goodbye-world"
          #   children: 
          #     - label: "Subsection"
          #       file: "02"
          #       id: "example-id"
        start-page: "01" # At which file should users start reading?
        # contents-page: "0-3-contents" # Your contents-page file, if you have one.
      epub:
        date: "2016-05-07" # YYYY-MM-DD e.g. publication date or last revision
        format: "Digital download" # e.g. Paperback, Digital download, Digital online
        identifier: "9780000000000" # e.g. ISBN or UUID
        image: "cover.jpg"
        start-page: "0-3-contents"
        contents-page: "0-3-contents"
        files: # add a value to any file to set any of the guide types listed in http://www.idpf.org/epub/20/spec/OPF_2.0.1_draft.htm#Section2.6
          - "0-0-cover": "cover"
          - "0-1-titlepage": "title-page"
          - "0-2-copyright": "copyright-page"
          - "0-3-contents": "toc"
          - "01": "text"
          - "02"
        toc: # For each menu item, include at least label and file (epub requires file). Optionally add id (for deep linking) and children.
          - label: "Cover"
            file: "0-0-cover"
          - label: "Title page"
            file: "0-1-titlepage"
          - label: "Copyright"
            file: "0-2-copyright"
          - label: "Contents"
            file: "0-3-contents"
          - label: "Chapter One"
            file: "01"
          - label: "Chapter Two"
            file: "02"
      screen-pdf:
        date: "2016-05-07" # YYYY-MM-DD e.g. publication or creation date
        format: "Digital download" # e.g. Paperback, Digital download, Digital online
        identifier: "" # e.g. ISBN or UUID
        image: "cover.jpg"
        files:
          - "0-1-titlepage"
          # - "0-2-copyright"
          # - "0-3-contents"
          - "01"
          # - "02"
        toc: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
          - label: "Useful Buddhist Teachings"
            file: "01"
      app:
        date: "2016-05-07" # YYYY-MM-DD e.g. publication date or last revision
        format: "Digital download" # e.g. Paperback, Digital download, Digital online
        identifier: "" # e.g. ISBN or UUID
        image: "cover.jpg"
        files:
          - "index"
          - "0-1-titlepage"
          - "0-2-copyright"
          - "0-3-contents"
          - "01": "Chapter One"
          - "02": "Chapter Two"
        nav: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
          - label: "Frontmatter"
            children:
              - label: "Cover"
                file: "index"
              - label: "Title page"
                file: "0-1-titlepage"
              - label: "Copyright"
                file: "0-2-copyright"
          - label: "Contents"
            file: "0-3-contents"
          - label: "Chapter One"
            file: "01"
            id: "1-hello-world"
          - label: "Chapter Two"
            file: "02"
            id: "2-goodbye-world"
            children: 
              - label: "Subsection"
                file: "02"
                id: "example-id"
        start-page: "0-3-contents" # At which file should users start reading?
        contents-page: "0-3-contents" # Your contents-page file, if you have one.
    # variants:
    #   - variant: myvariant
    #     identifier: ""
    #     products:
    #       print-pdf:
    #         identifier: ""